### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by iTrooz** [jcaesar/structstruck#7]
Hey, you might want to add a license to this project. By default, no one have any right to your code (so no one can use it)

https://choosealicense.com/

If you don't choose one: https://choosealicense.com/no-permission/

**Comment by jcaesar** [comment]
There is https://github.com/jcaesar/structstruck/blob/master/Cargo.toml#L4 but I don't assume that alone is enough.

If this is a "might be better to" issue, I'll leave it as is, but if you have a concrete problem with the situation ("want to use it for work project X but work has a strict license policy" or so), I can change it. (PRs welcome.)

**Comment by iTrooz** [comment]
This issue wasn't about changing the licence but more about setting one. I didn't see that there was a licence in Cargo.toml, because usually licence are displayed through a special LICENCE file (https://github.com/microsoft/vscode/blob/main/LICENSE.txt https://github.com/WerWolv/ImHex/blob/master/LICENSE https://github.com/rust-lang/crates.io/blob/master/LICENSE-APACHE https://github.com/rust-lang/crates.io/blob/master/LICENSE-MIT)

Note: github itself reads this file to show the project licence in the sidebar

I'd be glad to open a PR to add this file !

**Comment by jcaesar** [comment]
Aight, merged. I assume you don't need a new crate release with this? It is already on display on crates.io after all.
![image](https://user-images.githubusercontent.com/1753388/236953583-452ca7b9-1822-4e0c-a2af-9c98bfc913d3.png)

**Comment by iTrooz** [comment]
No, thank you !
